from m_dpp_common.rbac.admin import make_rbac_router
from m_dpp_common.rbac.engine import BoundRbac, RbacEngine, as_roles, principal_roles
from m_dpp_common.rbac.platform import (
    COMMON_RESOURCE_DEFAULTS,
    COMMON_RESOURCE_TYPES,
    FULL,
    NONE,
    READ,
    READ_UPDATE,
    WRITE,
    merge_resource_defaults,
    permissions_checksum,
    platform_definition_checksum,
)
from m_dpp_common.rbac.models import (
    ATTR_ORIGIN_DISCOVERED,
    ATTR_ORIGIN_MANUAL,
    AttrPermissionMixin,
    OrganisationRoleMixin,
    RbacAttributeMixin,
    ResourcePermissionMixin,
    RoleMixin,
)
from m_dpp_common.rbac.seed import (
    JRC_ROLES,
    NEW_ROLE_ATTR_DEFAULTS,
    NEW_ROLE_RESOURCE_DEFAULTS,
    fan_out_attribute,
    fan_out_role,
    seed_rbac,
)

__all__ = [
    "make_rbac_router",
    "RbacEngine",
    "BoundRbac",
    "principal_roles",
    "COMMON_RESOURCE_TYPES",
    "COMMON_RESOURCE_DEFAULTS",
    "merge_resource_defaults",
    "permissions_checksum",
    "platform_definition_checksum",
    "NONE",
    "READ",
    "READ_UPDATE",
    "WRITE",
    "FULL",
    "as_roles",
    "RoleMixin",
    "RbacAttributeMixin",
    "AttrPermissionMixin",
    "OrganisationRoleMixin",
    "ResourcePermissionMixin",
    "ATTR_ORIGIN_DISCOVERED",
    "ATTR_ORIGIN_MANUAL",
    "JRC_ROLES",
    "NEW_ROLE_RESOURCE_DEFAULTS",
    "NEW_ROLE_ATTR_DEFAULTS",
    "seed_rbac",
    "fan_out_role",
    "fan_out_attribute",
]
