/**
 * The wire types of an mdpp-app instance.
 *
 * The comparison types mirror what `GET /{path}/comparison` returns **exactly**.
 * They are read-only as far as every front-end is concerned: mdpp-app computes
 * each verdict, and a renderer's job is to display these fields, never to derive
 * `complies` / `within` / a sentence of its own. Two front-ends deriving the same
 * verdict independently would disagree the first time a rule moved.
 */

export type Gs1Level = "model" | "variant" | "batch" | "item";

export type TestStatus = "requested" | "in_progress" | "completed" | "error";
export type VerificationStatus = "verified" | "mismatch" | "unverified";
export type AnalysisType = "in_loco" | "submitted_data";

export type DeclarationReason = "initial" | "correction" | "spec_change" | "post_test";

/** A taxonomy node, as the comparison object names one. */
export interface FibreRef {
  slug: string;
  label: string;
}

export interface DeclaredComponentRef extends FibreRef {
  percentage: number;
  official_fibre: FibreRef | null;
}

export interface Declaration {
  version: number;
  is_current: boolean;
  declared_by: string;
  declared_by_name?: string | null;
  declared_at: string | null;
  reason: DeclarationReason;
  withdrawn_at: string | null;
  components: DeclaredComponentRef[];
  /** Present on a comparison's declaration: was this the version current when
   *  the test was requested, or one the caller forced with `declaration_version`? */
  at_test_time?: boolean;
}

// ── the three verdicts ───────────────────────────────────────────────────

export type OfficialVerdict = "complies" | "off";

export interface OfficialResult {
  /** `null` on an undeclared row — there is no declared fibre to comply with. */
  verdict: OfficialVerdict | null;
  declared_official: FibreRef | null;
  tested_official: FibreRef | null;
}

export type SpecificityRelationship =
  | "same"
  | "tested_is_descendant"
  | "tested_is_ancestor"
  | "same_official_other_branch"
  | "unrelated";

export interface SpecificityResult {
  relationship: SpecificityRelationship;
  declared_node: FibreRef;
  tested_node: FibreRef;
  confirmed_at_declared_depth: boolean;
  confirmed_official: boolean;
  /** Generated by mdpp-app. Render this; do not compose your own. */
  sentence: string;
}

export interface QuantityResult {
  declared_percentage: number;
  tested_percentage: number;
  /** tested − declared, in percentage points (signed). */
  difference: number;
  /** `null` when no node in the declared fibre's chain defines one. */
  tolerance: number | null;
  tolerance_from: FibreRef | null;
  tolerance_inherited: boolean;
  /** `null` means UNKNOWN (no tolerance), which is not the same as within. */
  within: boolean | null;
}

export type ComparisonRowKind = "matched" | "not_found" | "undeclared";

export interface ComparisonRow {
  kind: ComparisonRowKind;
  declared: (FibreRef & { percentage: number }) | null;
  tested: (FibreRef & { percentage: number; confidence: number | null }) | null;
  official: OfficialResult | null;
  specificity: SpecificityResult | null;
  quantity: QuantityResult | null;
  confidence: number | null;
}

export interface ComparisonFlag {
  code: string;
  message: string;
}

export interface ComparisonTest {
  id: string;
  laboratory_id: string;
  laboratory_name: string | null;
  ticket_number: string;
  status: TestStatus;
  requested_at: string | null;
  verification_status: VerificationStatus | null;
  analysis_type: AnalysisType | null;
  method_reference: string | null;
  analysed_at: string | null;
  reported_gs1_path: string | null;
}

/** One test versus one declaration. Never several tests merged. */
export interface TestComparison {
  test: ComparisonTest;
  declaration: Declaration | null;
  rows: ComparisonRow[];
  flags: ComparisonFlag[];
}

/** The whole `GET /{path}/comparison` body. */
export interface ComparisonResponse {
  gs1_path: string;
  level: Gs1Level | null;
  /** The declaration CURRENTLY on this path (each comparison carries its own). */
  declaration: Declaration | null;
  comparisons: TestComparison[];
  test_count: number;
  verified_test_count: number;
}

// ── listings ─────────────────────────────────────────────────────────────

export interface DeclarationListItem {
  id: string;
  gs1_path: string;
  level: Gs1Level | null;
  version: number;
  is_current: boolean;
  declared_by: string;
  declared_by_name: string | null;
  declared_at: string | null;
  reason: DeclarationReason;
  withdrawn_at: string | null;
  components: { slug: string; percentage: number }[];
}

export interface TestListItem {
  id: string;
  gs1_path: string;
  level: Gs1Level | null;
  laboratory_id: string;
  laboratory_name: string | null;
  ticket_number: string;
  status: TestStatus;
  status_message: string | null;
  requested_at: string | null;
  last_polled_at: string | null;
  withdrawn_at: string | null;
  analysis_type: AnalysisType | null;
  verification_status: VerificationStatus | null;
  method_reference: string | null;
  analysed_at: string | null;
  has_result: boolean;
}

export interface Page<T> {
  total: number;
  limit: number;
  offset: number;
  items: T[];
}

export interface PathCounts {
  gs1_path: string | null;
  level: Gs1Level | null;
  declarations: number;
  tests: number;
  known: boolean;
}

export interface DeclarationQuery {
  pathPrefix?: string;
  level?: Gs1Level | "";
  declaredBy?: string;
  currentOnly?: boolean;
  includeWithdrawn?: boolean;
  limit?: number;
  offset?: number;
}

export interface TestQuery {
  pathPrefix?: string;
  level?: Gs1Level | "";
  status?: TestStatus | "";
  laboratoryId?: string;
  analysisType?: AnalysisType | "";
  sort?: "requested_at" | "-requested_at" | "analysed_at" | "-analysed_at";
  includeWithdrawn?: boolean;
  limit?: number;
  offset?: number;
}

/** A new declaration version: fibre slug + percentage rows, never raw JSON. */
export interface DeclarationCreate {
  declared_by: string;
  reason: DeclarationReason;
  components: { fibre: string; percentage: number }[];
}

/** Registering a test takes only the lab and its ticket. */
export interface TestRegister {
  laboratory_id: string;
  ticket_number: string;
}

/** A node of the fibre taxonomy, for the composition editor's fibre picker. */
export interface FibreNode {
  id: string;
  slug: string;
  label: string;
  parent_id: string | null;
  legal_name: boolean;
  attrs?: Record<string, unknown> | null;
}
