/**
 * The wire types of an mdpp-app instance.
 *
 * The comparison types mirror what `GET /{path}/comparison` returns **exactly**.
 * They are read-only as far as every front-end is concerned: mdpp-app computes
 * each verdict, and a renderer's job is to display these fields, never to derive
 * `complies` / `within` / a sentence of its own. Two front-ends deriving the same
 * verdict independently would disagree the first time a rule moved.
 */

export type Gs1Level = "model" | "variant" | "batch" | "item";

export type TestStatus = "requested" | "in_progress" | "completed" | "error";
export type VerificationStatus = "verified" | "mismatch" | "unverified";
export type AnalysisType = "in_loco" | "submitted_data";

export type DeclarationReason = "initial" | "correction" | "spec_change" | "post_test";

/** A taxonomy node, as the comparison object names one. */
export interface FibreRef {
  slug: string;
  label: string;
}

export interface DeclaredComponentRef extends FibreRef {
  percentage: number;
  official_fibre: FibreRef | null;
}

export interface Declaration {
  version: number;
  is_current: boolean;
  declared_by: string;
  declared_by_name?: string | null;
  declared_at: string | null;
  reason: DeclarationReason;
  withdrawn_at: string | null;
  components: DeclaredComponentRef[];
  /** Present on a comparison's declaration: how it came to be the one compared
   *  against.
   *  - `at_test_time` — the claim that was live when the test was requested
   *  - `declared_after_test` — nothing was claimed then; this came afterwards
   *  - `selected` — a caller asked for a specific version */
  basis?: "at_test_time" | "declared_after_test" | "selected";
  /** @deprecated `basis === "at_test_time"`. */
  at_test_time?: boolean;
}

// ── the three verdicts ───────────────────────────────────────────────────

export type OfficialVerdict = "complies" | "off";

export interface OfficialResult {
  /** `null` on an undeclared row — there is no declared fibre to comply with. */
  verdict: OfficialVerdict | null;
  declared_official: FibreRef | null;
  tested_official: FibreRef | null;
}

export type SpecificityRelationship =
  | "same"
  | "tested_is_descendant"
  | "tested_is_ancestor"
  | "same_official_other_branch"
  | "unrelated";

export interface SpecificityResult {
  relationship: SpecificityRelationship;
  declared_node: FibreRef;
  tested_node: FibreRef;
  confirmed_at_declared_depth: boolean;
  confirmed_official: boolean;
  /** Generated by mdpp-app. Render this; do not compose your own. */
  sentence: string;
}

export interface QuantityResult {
  declared_percentage: number;
  tested_percentage: number;
  /** tested − declared, in percentage points (signed). */
  difference: number;
  /** `null` when no node in the declared fibre's chain defines one. */
  tolerance: number | null;
  tolerance_from: FibreRef | null;
  tolerance_inherited: boolean;
  /** `null` means UNKNOWN (no tolerance), which is not the same as within. */
  within: boolean | null;
}

export type ComparisonRowKind = "matched" | "not_found" | "undeclared";

export interface ComparisonRow {
  kind: ComparisonRowKind;
  declared: (FibreRef & { percentage: number }) | null;
  tested: (FibreRef & { percentage: number; confidence: number | null }) | null;
  official: OfficialResult | null;
  specificity: SpecificityResult | null;
  quantity: QuantityResult | null;
  confidence: number | null;
}

export interface ComparisonFlag {
  code: string;
  message: string;
}

export interface ComparisonTest {
  id: string;
  /** The organisation that ASKED for the test — distinct from the lab that ran
   *  it. Provenance, derived by mdpp-app from the caller's principal. */
  requested_by: string;
  requested_by_name: string | null;
  laboratory_id: string;
  laboratory_name: string | null;
  ticket_number: string;
  status: TestStatus;
  requested_at: string | null;
  verification_status: VerificationStatus | null;
  analysis_type: AnalysisType | null;
  method_reference: string | null;
  analysed_at: string | null;
  reported_gs1_path: string | null;
}

/** One test versus one declaration. Never several tests merged. */
export interface TestComparison {
  test: ComparisonTest;
  declaration: Declaration | null;
  rows: ComparisonRow[];
  flags: ComparisonFlag[];
}

/** The whole `GET /{path}/comparison` body. */
export interface ComparisonResponse {
  gs1_path: string;
  level: Gs1Level | null;
  /** The declaration CURRENTLY on this path (each comparison carries its own). */
  declaration: Declaration | null;
  comparisons: TestComparison[];
  test_count: number;
  verified_test_count: number;
}

// ── listings ─────────────────────────────────────────────────────────────

export interface DeclarationListItem {
  id: string;
  gs1_path: string;
  level: Gs1Level | null;
  version: number;
  is_current: boolean;
  declared_by: string;
  declared_by_name: string | null;
  declared_at: string | null;
  reason: DeclarationReason;
  withdrawn_at: string | null;
  components: { slug: string; percentage: number }[];
}

export interface TestListItem {
  id: string;
  gs1_path: string;
  level: Gs1Level | null;
  requested_by: string;
  requested_by_name: string | null;
  laboratory_id: string;
  laboratory_name: string | null;
  ticket_number: string;
  status: TestStatus;
  status_message: string | null;
  requested_at: string | null;
  last_polled_at: string | null;
  withdrawn_at: string | null;
  /** Why it was withdrawn — the reason a withdrawn test is kept rather than
   *  deleted. A row nobody can explain is no better than a missing one. */
  withdrawn_reason: string | null;
  analysis_type: AnalysisType | null;
  verification_status: VerificationStatus | null;
  method_reference: string | null;
  analysed_at: string | null;
  has_result: boolean;
}

export interface Page<T> {
  total: number;
  limit: number;
  offset: number;
  items: T[];
}

export interface PathCounts {
  gs1_path: string | null;
  level: Gs1Level | null;
  declarations: number;
  tests: number;
  known: boolean;
}

export interface DeclarationQuery {
  pathPrefix?: string;
  level?: Gs1Level | "";
  declaredBy?: string;
  currentOnly?: boolean;
  includeWithdrawn?: boolean;
  limit?: number;
  offset?: number;
}

export interface TestQuery {
  pathPrefix?: string;
  level?: Gs1Level | "";
  status?: TestStatus | "";
  laboratoryId?: string;
  requestedBy?: string;
  analysisType?: AnalysisType | "";
  sort?: "requested_at" | "-requested_at" | "analysed_at" | "-analysed_at";
  includeWithdrawn?: boolean;
  limit?: number;
  offset?: number;
}

/** A new declaration version: fibre slug + percentage rows, never raw JSON.
 *
 *  `declared_by` is deliberately absent — mdpp takes the declaring organisation
 *  from the one you are acting for, never from the payload. */
export interface DeclarationCreate {
  reason: DeclarationReason;
  components: { fibre: string; percentage: number }[];
}

/** Registering a test takes only the lab and its ticket. */
export interface TestRegister {
  laboratory_id: string;
  ticket_number: string;
}

/** A node of the fibre taxonomy. */
export interface FibreNode {
  id: string;
  slug: string;
  label: string;
  parent_id: string | null;
  /** A legally-binding fibre name under EU 1007/2011 (wool, cotton, polyester…). */
  legal_name: boolean;
  legal_ref?: string | null;
  /** Open bag. `tolerance` (absolute percentage points) lives here and is what
   *  every quantity verdict is measured against. */
  attrs?: Record<string, unknown> | null;
  created_at?: string;
  updated_at?: string;
  removed_at?: string | null;
}

export interface FibreNodeCreate {
  label: string;
  slug?: string;
  parent_id?: string | null;
  legal_name?: boolean;
  legal_ref?: string | null;
  attrs?: Record<string, unknown>;
}

export interface FibreNodeUpdate {
  label?: string;
  slug?: string;
  parent_id?: string | null;
  legal_name?: boolean;
  legal_ref?: string | null;
  /** A merge patch onto the stored bag: `null` removes a key. */
  attrs?: Record<string, unknown>;
}

/** The resolved principal as mdpp-app reports it (`GET /me`). */
export interface MdppPrincipal {
  sub: string | null;
  anonymous: boolean;
  /** Why it is anonymous — e.g. "unknown subject", "no identity supplied". */
  reason: string | null;
  organisation: { id: string; name: string } | null;
  roles: string[];
  permissions?: Record<string, Record<string, boolean>>;
}
