import { useState } from "react";
import { Button, Chip, Notice } from "../../design";
import type {
  TestComparison,
  ComparisonRow,
  Declaration,
  OfficialResult,
  QuantityResult,
  SpecificityResult,
} from "../../mdpp/types";
import s from "./Comparison.module.css";

/**
 * Renders ONE comparison — one test versus one declaration — exactly as
 * mdpp-app computed it.
 *
 * **This component computes nothing.** Every verdict, sentence, tolerance and
 * flag on screen is a field of the object mdpp-app returned. mdpp-app's admin,
 * dpp-app's Molecular tab and later passport-app all render through this one
 * component, so the apps cannot drift in how a verdict is shown — and because
 * the component has no logic, there is nothing for them to drift *about*.
 *
 * Wording is deliberately neutral throughout: a row is "flagged for review",
 * never an accusation. A gap between a declaration and a test is a prompt to
 * look, not a finding of fault.
 */
export interface ComparisonProps {
  comparison: TestComparison;
  /** Show the collapsible legend under the table. Default true. */
  showLegend?: boolean;
  /** A note the host adds, e.g. "inherited — applies to this item". */
  contextNote?: React.ReactNode;
}

const REL_LABEL: Record<string, string> = {
  same: "at declared depth",
  tested_is_descendant: "more specific than declared",
  tested_is_ancestor: "less specific than declared",
  same_official_other_branch: "same legal fibre, different branch",
  unrelated: "unrelated",
};

function fmtPct(v: number | null | undefined): string {
  return v === null || v === undefined ? "—" : `${Number(v.toFixed(3))}%`;
}

function fmtDiff(v: number): string {
  const n = Number(v.toFixed(3));
  return `${n > 0 ? "+" : ""}${n} pp`;
}

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString();
}

// ── the three verdict cells ──────────────────────────────────────────────

function OfficialCell({ official }: { official: OfficialResult | null }) {
  if (!official || official.verdict === null) return <span className={s.dash}>—</span>;
  const complies = official.verdict === "complies";
  return (
    <div className={s.fibre}>
      <Chip tone={complies ? "ok" : "warn"} dot>{complies ? "complies" : "off"}</Chip>
      {official.tested_official && (
        <span className={s.fibreSub}>{official.tested_official.label}</span>
      )}
    </div>
  );
}

function SpecificityCell({ specificity }: { specificity: SpecificityResult | null }) {
  if (!specificity) return <span className={s.dash}>—</span>;
  return (
    <div className={s.fibre}>
      {/* the sentence is generated by mdpp-app — never composed here */}
      <span className={s.sentence}>{specificity.sentence}</span>
      <span className={s.fibreSub}>{REL_LABEL[specificity.relationship] ?? specificity.relationship}</span>
    </div>
  );
}

function QuantityCell({ quantity }: { quantity: QuantityResult | null }) {
  if (!quantity) return <span className={s.dash}>—</span>;
  // `within: null` means no tolerance is defined anywhere in the declared
  // fibre's chain. Unknown is NOT a pass, so it renders neutral, not green.
  const tone = quantity.within === null ? "neutral" : quantity.within ? "ok" : "warn";
  const label = quantity.within === null ? "no tolerance set" : quantity.within ? "within" : "outside";
  return (
    <div className={s.fibre}>
      <span className={s.num}>{fmtDiff(quantity.difference)}</span>
      <Chip tone={tone} dot>{label}</Chip>
      {quantity.tolerance !== null && (
        <span className={s.tolNote}>
          tolerance ±{quantity.tolerance} pp
          {quantity.tolerance_inherited && quantity.tolerance_from
            ? ` · inherited from ${quantity.tolerance_from.label}`
            : " · set on this fibre"}
        </span>
      )}
    </div>
  );
}

// ── rows ─────────────────────────────────────────────────────────────────

function Row({ row }: { row: ComparisonRow }) {
  const undeclared = row.kind === "undeclared";
  return (
    <tr className={undeclared ? s.rowUndeclared : undefined}>
      <td>
        {row.declared ? (
          <div className={s.fibre}>
            <span>{row.declared.label}</span>
            <span className={s.fibreSub}>{row.declared.slug}</span>
          </div>
        ) : (
          <Chip tone="warn">not declared</Chip>
        )}
      </td>
      <td className={s.num}>{row.declared ? fmtPct(row.declared.percentage) : <span className={s.dash}>—</span>}</td>
      <td>
        {row.tested ? (
          <div className={s.fibre}>
            <span>{row.tested.label}</span>
            <span className={s.fibreSub}>{row.tested.slug}</span>
          </div>
        ) : (
          <Chip tone="warn">not found</Chip>
        )}
      </td>
      <td className={s.num}>{row.tested ? fmtPct(row.tested.percentage) : <span className={s.dash}>—</span>}</td>
      <td><OfficialCell official={row.official} /></td>
      <td><SpecificityCell specificity={row.specificity} /></td>
      <td><QuantityCell quantity={row.quantity} /></td>
      <td className={s.num}>
        {row.confidence === null || row.confidence === undefined
          ? <span className={s.dash}>—</span>
          : `${Math.round(row.confidence * 100)}%`}
      </td>
    </tr>
  );
}

// ── the declaration the test was compared against ────────────────────────

function Basis({ declaration }: { declaration: Declaration | null }) {
  if (!declaration) {
    return (
      <div className={s.basis}>
        {/* Deliberately says nothing about ancestors: this service is flat and
            has no way to know whether one exists. A viewer that holds the
            hierarchy passes the effective claim in and this branch is not
            reached. Promising an inherited claim that may not exist would be
            worse than saying plainly what IS known. */}
        <span>Nothing has been declared on this identifier, so there is no claim to compare against.</span>
      </div>
    );
  }
  const basis = declaration.basis ?? (declaration.at_test_time === false ? "selected" : "at_test_time");
  return (
    <div className={s.basis}>
      <span>
        Compared against <b>version {declaration.version}</b>
        {declaration.inherited && declaration.source_gs1_path && (
          <>
            {" "}declared on <code>{declaration.source_gs1_path}</code>
          </>
        )}
      </span>
      {/* An inherited claim is named, never implied: a verdict rendered against
          a claim made on another identifier must say which, or a reader cannot
          tell whose composition was actually tested. */}
      {declaration.inherited && <Chip>inherited claim</Chip>}
      <span className={s.basisNote}>
        {basis === "selected"
          ? "a version you selected, not the one current at test time"
          : basis === "declared_after_test"
            ? "declared AFTER this test was requested — nothing was claimed when the sample was sent"
            : "the version current when this test was requested"}
      </span>
      <span className={s.basisNote}>declared {fmtDate(declaration.declared_at)}</span>
      {basis === "declared_after_test" && <Chip tone="warn">declared after the test</Chip>}
      {declaration.withdrawn_at && <Chip tone="warn">withdrawn since</Chip>}
    </div>
  );
}

// ── legend ───────────────────────────────────────────────────────────────

function Legend() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <Button className={s.legendToggle} size="sm" variant="ghost" onClick={() => setOpen((v) => !v)}>
        {open ? "Hide legend" : "What do these three columns mean?"}
      </Button>
      {open && (
        <dl className={s.legend}>
          <div>
            <dt>Official fibre</dt>
            <dd>
              Whether the tested fibre carries the same legally-binding fibre name
              (EU 1007/2011) as the declared one. Merino and rambouillet are both
              "wool" in law, so either confirms a wool claim.
            </dd>
          </div>
          <div>
            <dt>Specificity</dt>
            <dd>
              Whether the test reached the depth that was claimed. A test may be
              more specific than the declaration, less specific, or land on a
              neighbouring fibre under the same legal name.
            </dd>
          </div>
          <div>
            <dt>Quantity</dt>
            <dd>
              Tested minus declared, in percentage points, against the tolerance
              for the declared fibre. A tolerance set on a broad family is
              inherited by everything beneath it.
            </dd>
          </div>
        </dl>
      )}
    </>
  );
}

// ── the component ────────────────────────────────────────────────────────

export function Comparison({ comparison, showLegend = true, contextNote }: ComparisonProps) {
  const { test, declaration, rows, flags } = comparison;
  const verified = test.verification_status === "verified";

  return (
    <div className={s.wrap}>
      <div className={s.head}>
        <Chip tone={verified ? "ok" : "warn"} dot>
          {verified ? "verified" : test.verification_status ?? "unverified"}
        </Chip>
        {test.analysis_type && (
          <Chip tone={test.analysis_type === "in_loco" ? "neutral" : "warn"}>
            {test.analysis_type === "in_loco" ? "in-loco analysis" : "client-submitted data"}
          </Chip>
        )}
        {contextNote}
      </div>

      <div className={s.headMeta}>
        <span>method <b>{test.method_reference ?? "—"}</b></span>
        <span>requested by <b>{test.requested_by_name ?? "—"}</b></span>
        <span>lab <b>{test.laboratory_name ?? test.laboratory_id}</b></span>
        <span>ticket <b>{test.ticket_number}</b></span>
        <span>analysed <b>{fmtDate(test.analysed_at)}</b></span>
      </div>

      {/* shown once per comparison, not per row */}
      <Basis declaration={declaration} />

      {/* The eight verdict columns are the point of this component, so they are
          not dropped in a narrow host — but they must scroll inside their own
          box rather than widening the card they sit in. */}
      <div className={s.tableScroll}>
      <table className={s.table}>
        <thead>
          <tr>
            <th>Declared fibre</th>
            <th>Declared</th>
            <th>Tested fibre</th>
            <th>Tested</th>
            <th>Official fibre</th>
            <th>Specificity</th>
            <th>Quantity</th>
            <th>Confidence</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <Row key={`${row.kind}-${row.declared?.slug ?? row.tested?.slug ?? i}`} row={row} />
          ))}
        </tbody>
      </table>
      </div>

      {flags.length > 0 && (
        <div className={s.flags}>
          {flags.map((f) => (
            <Notice key={f.code} tone="warn">{f.message}</Notice>
          ))}
        </div>
      )}

      {showLegend && <Legend />}
    </div>
  );
}
